# Parameters used in tomography

Source:
    p0 : !!python/float 2e5
    wl : !!python/float 7.29e-11
    th_s : !!python/float 2e-4

Exp_geom:
    defocus  : !!python/float 400e-05
    det_dist : !!python/float 14.0e-03

Detector:
    fs_size    : 100
    ss_size    : 100

    pixelsize_x : !!python/float 55e-8
    pixelsize_y : !!python/float 55e-8

Lens:
    focus_x : !!python/float 1.2e-3
    focus_y : !!python/float 1.0e-3
    ap_x    : !!python/float 40e-06
    #ap1_y : 2
    #ap2_x : 2
    ap_y    : !!python/float 40e-6
    alpha_x : -0.05
    alpha_y : -0.05
    #Lens’ abberations center point [0.0 - 1.0].
    x_abcen : 0.5
    y_abcen : 0.5

#Quad_parameter:
#    epsabs = 1.49e-08
#    epsrel = 1.49e-08
#    limit = 50
